<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head> 
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/> 

 <!-- Highslide image gallery -->
<script type="text/javascript" src="highslide/highslide-full.js"></script>
<link rel="stylesheet" type="text/css" href="highslide/highslide.css" />
<!--[if lt IE 7]>
<link rel="stylesheet" type="text/css" href="highslide/highslide-ie6.css" />
<![endif]-->

<script type="text/javascript">
//<![CDATA[
hs.registerOverlay({
	html: '<div class="closebutton" onclick="return hs.close(this)" title="Close"></div>',
	position: 'top right',
	fade: 2 // fading the semi-transparent overlay looks bad in IE
});

hs.graphicsDir = 'highslide/graphics/';
//hs.wrapperClassName = 'borderless';
hs.align = 'center';
hs.transitions = ['expand', 'crossfade'];
hs.outlineType = 'rounded-white';
hs.fadeInOut = false; 
hs.dimmingOpacity = 0.66;

// Add the controlbar
hs.addSlideshow({
	//slideshowGroup: 'group1',
	interval: 3000,
	repeat: false,
	useControls: true,
	fixedControls: 'fit',
	overlayOptions: {
		opacity: .75,
		position: 'bottom center',
		hideOnMouseOut: true
	}
});

//]]>
</script>
 <!-- End Highslide -->

<title>Visualization Library: Visualization Library Reference Documentation</title> 

<link href="tabs.css" rel="stylesheet" type="text/css"/> 
<link href="search/search.css" rel="stylesheet" type="text/css"/> 
<script type="text/javaScript" src="search/search.js"></script> 
<link href="docs.css" rel="stylesheet" type="text/css"/> 
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-1058203-6']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>


<table border="0" style="margin: 0px; margin-bottom: 25px; padding: 0px; border: 0px;" width="100%">
<tr>
	<td align="left" valign="top" style="text-align: left; margin: 20px; font-family: Verdana; font-size: 10px;">
		<h1 style="text-align: left; font-size: 32px; font-family: Arial; border: 0px; margin: 0px; margin-bottom: 10px; margin-top: 10px;">

			<a href="http://www.visualizationlibrary.com">Visualization Library</a>
		</h1>
		<span style="color: gray;">A lightweight C++ OpenGL middleware for 2D/3D graphics</span>
	</td>
	<td align="right" valign="top">
		<small>
			<a href="index.html">[Home]</a>

			<a href="pag_guides.html">[Tutorials]</a>
			<a href="annotated.html">[All Classes]</a>
			<a href="pag_main_classes.html">[Grouped Classes]</a>
		</small>
	</td>
</tr>
</table>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>

<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.html"><span>Main&#160;Page</span></a></li>
      <li><a href="namespaces.html"><span>Namespaces</span></a></li>
      <li><a href="annotated.html"><span>Classes</span></a></li>
      <li><a href="files.html"><span>Files</span></a></li>

      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>

      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Downloads</h1>  </div>

<!---------------------------------------------------------------------------->

<div style="padding: 10px">

	<h2>GENERAL INFO</h2>
	<p>First of all you might want to have a look at the <a href="http://www.visualizationlibrary.org/documentation/pag_changelog.html">Changelog</a>.</p>
	<p>Remember to set the <b>VL_DATA_PATH</b> environment variable to the directory containing the sample data in order to run the demos and tests included in VL.</p>
	<!-- p>You can also have a look at the complete <a target=_blank href="http://code.google.com/p/visualizationlibrary/source/list">SVN commit logs</a> </p -->

    <h2>GIT REPOSITORY</h2>
    <p>The latest version of Visualization Library can be checked out with:</p>
    <p><font face="Courier New">git clone https://github.com/MicBosi/visualizationlibrary.git</font></p>
     
    <h2>RELEASES &amp; DOWNLOADS</h2>
    <p><font face="Courier New"><a href="https://github.com/MicBosi/visualizationlibrary/releases">github.com/MicBosi/visualizationlibrary/releases</a></font></p>
     
	<h2 id="toc3">PACKAGES</h2>
	<p><b><font color=orange>[DEV MILESTONE]</font></b> = Relatively stable distribution containing the latest features. Compilation on MSVC and GCC works and regression tests passed, with the possible exception of some GUI bindings not working. No critical bugs should be present.</p>
	<p><b><font color=green>[STABLE]</font></b> = Official stable release.</p>

<?php 
if ($handle = opendir('../downloads')) {
    /* This is the correct way to loop over the directory. */
		// Note that !== did not exist until 4.0.0-RC2
		$j = 0;
		$files = array();
		$version_set = array();
    while (false !== ($file = readdir($handle))) 
		{
			if ( strpos($file, ".pureftpd-upload.") !== FALSE )
				continue;

			if ( is_dir('../downloads/'.$file) == TRUE )
				continue;

			if ($file != "." && $file != "..") 
			{
				$j++;

				$description = "0-[UNKNOWN]";
				if ( strpos($file, "-mgw-") !== FALSE )
					$description = "4-MinGW Binaries";
				else
				if ( strpos($file, "-vc8-") !== FALSE )
					$description = "4-Visual C++ 2005 Binaries";
				else
				if ( strpos($file, "-vc9-") !== FALSE )
					$description = "4-Visual C++ 2008 Binaries";
				else
				if ( strpos($file, "Visualization_Library_SDK-data") !== FALSE )
					$description = "3-Sample Data";
				else
				if ( strpos($file, "Visualization_Library_SDK-src") !== FALSE )
				{
					$description = "1-Sources";
				}
				else
				if ( strpos($file, "chm") !== FALSE )
				{
					$description = "3-Documentation (CHM)";
				}
				else
				if ( strpos($file, "Visualization_Library_SDK-docs") !== FALSE )
				{
					$description = "2-Documentation (HTML)";
				}
				else
				if ( strpos($file, "Visualization_Library_SDK-") !== FALSE )
				{
					$description = "1-Sources & Data";
				}
				else
				{
					echo "skipping=".$file."<br>";
					continue;
				}

				$files[$j]['name'] = $file;
				$files[$j]['size'] = number_format(filesize('../downloads/'.$file)/1024,0);
				$files[$j]['date'] = date("F/d/Y", filemtime('../downloads/'.$file));
				if ($description == "1-Sources & Data")
					list($file_name, $file_ver) = split("-",$file);
				else
					list($file_name, $file_type, $file_ver) = split("-",$file);

				list($ver_maj, $ver_min, $ver_pat) = split('\.', $file_ver);
				$files[$j]['release'] = $ver_maj.".".$ver_min.".".$ver_pat;
				$files[$j]['ver_maj'] = $ver_maj;
				$files[$j]['ver_min'] = $ver_min;
				$files[$j]['ver_pat'] = $ver_pat;
				$files[$j]['description'] = $description;

				$version_set[$files[$j]['release']][$j] = $files[$j];
			}
		}
    closedir($handle);
		
		function file_array_sort($a, $b)
		{
			if ($a['description'] != $b['description'])
				return strcmp($a['description'], $b['description']);
			else
			if ($a['size'] != $b['size'])
				return strcmp($a['size'], $b['size']);
			else
			/*if ($a['ver_maj'] != $b['ver_maj'])
				return strcmp($a['ver_maj'], $b['ver_maj']);
			else
			if ($a['ver_min'] != $b['ver_min'])
				return strcmp($a['ver_min'], $b['ver_min']);
			else
			if ($a['ver_pat'] != $b['ver_pat'])
				return strcmp($a['ver_pat'], $b['ver_pat']);
			else*/
			return 0;
		}
		
		krsort($version_set);
		$j = 0;
		echo "<table border=0 cellspacing=1 cellpadding=7>\n";
		foreach($version_set as $version => $file_array)
		{
			$v1 = $v2 = $v3 = 0;
			sscanf($version, "%d.%d.%d", $v1, $v2, $v3 );
			$stable = ($v3 % 2) ? "<font color=orange>[DEV MILESTONE]</font>" : "<font color=green>[STABLE]</font>";
			echo "<tr>";
			echo "<td colspan=4 style='font-family: Verdana; padding-top: 15px; padding-left: 0px'><b>".$stable." Version ".$version."</b></td>\n";
			echo "</tr>";
			
			usort($file_array, "file_array_sort");

			foreach($file_array as $i => $file )
			{
				$j++;
				$style="background-color: #FFF";
				if ($j % 2 == 1)
					$style="background-color: #E0E0E0";
					
				$file['description'] = substr($file['description'],2);
				
				if ( $file['description'] == '[UNKNOWN]')
					continue;
					
				echo "<tr>";
				echo "<td style='$style'>".$file['description']."</td>";
				echo "<td style='$style'><a onClick=\"javascript: pageTracker._trackPageview('downloads/".$file['name']."');\" href='../downloads/".$file['name']."'>".$file['name']."</a></td>";
				echo "<td style='$style'>".$file['size']." Kb</td>";
				echo "<td style='$style'>".$file['date']."</td>";
				echo "</tr>\n";
			}
			
		}
		echo "</table>";
}
?>

<h2>DOWNLOADS ARCHIVE</h2>
<p>You can find older versions of Visualization Library in the <a href="http://www.visualizationlibrary.org/documentation/downloads_old.php">Downloads Archive</a> page.</p>

<h2>COMPILING VISUALIZATION LIBRARY</h2>
<p>Visualization Library uses CMake as its building system and can target several environments and compilers. At the moment we officially support the following platforms:</p> 
 
<ul> 
    <li>Windows: Visual Studio 2005, 2008 and 2010</li> 
    <li>Windows: MinGW</li> 
    <li>Linux: GNU make/gcc</li> 
    <li>Mac OS X: Xcode</li> 
</ul> 
 
<p>For more information please read <a href="http://www.visualizationlibrary.org/documentation/pag_install.html">Compiling and Installing Visualization Library</a>.</p> 

<br />
<br />
<br />
</div>

<!---------------------------------------------------------------------------->

    <script type="text/javascript" src="/jetcms/sites/all/modules/google_analytics/googleanalytics.js?S"></script> 
<script type="text/javascript"> 
<!--//--><![CDATA[//><!--
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
//--><!]]> 
</script> 
<script type="text/javascript"> 
<!--//--><![CDATA[//><!--
var pageTracker = _gat._getTracker("UA-1058203-6");pageTracker._trackPageview();
//--><!]]> 
</script> 
</html> 